### ISSUE TITLE
readString denial of service

### ISSUE THREAD

**Issue by asarubbo** [libming/libming#70]
please see the following advisory:
http://seclists.org/fulldisclosure/2017/May/106

**Comment by epozuelo** [comment]
So the fix is commit 6eca133ee9985

I wonder how this can fix a denial of service if the fix calls exit(). Surely instead of crashing (or other worse behaviour) the application will still exit unexpectedly? I wonder if it wouldn't be better to return some error code down to the caller?

**Comment by carnil** [comment]
This issue was assigned CVE-2017-8782

**Comment by strk** [comment]
There are many error paths taking to `exit()` call, it's a module meant to be used by utility functions, not by the library itself (which is an output library). That said, upon re-reading the full report I realize the problem was not with checking `realloc` return but to check `buflen` value. I guess we should check for the boundary of that `buflen`, after changing it to unsigned int ...

**Comment by strk** [comment]
Please see if you like befb7439c2cf4768bcca09651d6325e8f078e992 more

**Comment by epozuelo** [comment]
That looks good, thanks.
